# Generated by Django 4.0.1 on 2022-02-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tag_text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
